version: '3'
services:
  yosemite-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/uploads
    depends_on:
      - redis
      - ollama
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

volumes:
  redis-data:
